// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7JdPqQUe37teryzMsrg1vn_fdeTtgPhM',
    appId: '1:18066626482:web:394fe3e5f664a258e536ab',
    messagingSenderId: '18066626482',
    projectId: 'functionstest-e8655',
    authDomain: 'functionstest-e8655.firebaseapp.com',
    storageBucket: 'functionstest-e8655.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYC348Bcrc1QJCjYbkqDrOpu3xMGpT6mY',
    appId: '1:18066626482:android:babe2bd8a6a48122e536ab',
    messagingSenderId: '18066626482',
    projectId: 'functionstest-e8655',
    storageBucket: 'functionstest-e8655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCCWliGIp3sIET4S7H6QSrG4RWgbncgOA',
    appId: '1:18066626482:ios:229e4f96dd4e7767e536ab',
    messagingSenderId: '18066626482',
    projectId: 'functionstest-e8655',
    storageBucket: 'functionstest-e8655.appspot.com',
    iosClientId: '18066626482-aaomdetnlk20n1nl7qkpppo1ll1k798s.apps.googleusercontent.com',
    iosBundleId: 'com.example.counter',
  );
}
